### ISSUE TITLE
web page hosting

### ISSUE THREAD

**Issue by Magikarplvl4** [RuurdBijlsma/PlexClient#1]
Hi there,

I saw your link on reddit, and would like to say: What a lovely interface!!1
I was wondering, is it possible to host the webviewer on your own?
If yes: do you have some instructions?

**Comment by RuurdBijlsma** [comment]
If you have npm/nodejs installed, you can do:

1. `git clone https://github.com/RuurdBijlsma/PlexClient`
2. `cd PlexClient`
3. `npm i`
4. `npm run build`
5. Then host the created `/.dist` folder somewhere, for example GitHub pages can host it for free.

You can also just install the Electron application https://github.com/RuurdBijlsma/PlexClient/releases/tag/0.4.0. If you use Linux or Mac you'll have to build the app yourself with `npm run electron:build` although I'm not sure if the embedded mpv player will work, haven't tested it outside of Windows.
