### ISSUE TITLE
Libraries not visible

### ISSUE THREAD

**Issue by kopiezzo** [RuurdBijlsma/PlexClient#2]
Hey! Im trying to test your app with my server and it connects fine, but after it connects it doesn't show any libraries. Any reason for that?

![plex](https://user-images.githubusercontent.com/15052907/121723743-3166aa00-cae7-11eb-8c78-1054ed4aac48.PNG)

**Comment by RuurdBijlsma** [comment]
You can open console with the tilde key (`) to get more info about what's wrong. Don't expect too much from this application though. I don't even use it myself anymore
